CREATE TABLE DISTRICT (D_ID NUMBER(2, 0), D_W_ID 
  NUMBER(4, 0), D_YTD NUMBER(12, 2), D_TAX NUMBER(4, 4), 
  D_NEXT_O_ID NUMBER, D_NAME VARCHAR2(10), D_STREET_1 
  VARCHAR2(20), D_STREET_2 VARCHAR2(20), D_CITY VARCHAR2(20), 
  D_STATE CHAR(2), D_ZIP CHAR(9)) PCTFREE 10;