CREATE TABLE ORDER_LINE (OL_O_ID NUMBER, OL_D_ID NUMBER, 
  OL_W_ID NUMBER, OL_NUMBER NUMBER, OL_DELIVERY_D DATE, OL_I_ID 
  NUMBER, OL_SUPPLY_W_ID NUMBER, OL_QUANTITY NUMBER, OL_AMOUNT 
  NUMBER(6, 2), OL_DIST_INFO CHAR(24)) PCTFREE 10;